# Google Trends Project

This project is a part of the Portfolio for [Alyssa-Weber](https://github.com/Alyssa-Weber/Portfolio.git)

#### -- Project Status: [Completed]

## Project Intro/Objective

This project aims to showcase an unconventional way to collect data using Google Trends.

### Methods Used

-   Data Collection
-   APA style write-up

## Project Description

-   This project investigates whether or not standards-based grading impacts outcomes such as rigor, graduation rates, and post-secondary acceptance.
-   Uses [Google Trends](https://trends.google.com/trends/) as the main source of data collection.
-   Explores Minnesota's push towards standards-based grading using visuals from Google search histories.
-   Implies a need for a more extensive data set and analysis to draw specific conclusions about the impacts of standards-based grading.

## Needs of this project

-   data collection/ research
-   write-up/reporting

## Featured Deliverables

-   [Paper](https://github.com/Alyssa-Weber/Portfolio/blob/main/%231%20-%20Google%20Trends%20Project/Standards%20Based%20Grading%20Paper.docx)
-   [Presentation](https://github.com/Alyssa-Weber/Portfolio/blob/main/%231%20-%20Google%20Trends%20Project/Standards%20Based%20Grading%20Presentation.pptx)

## Contributing Members

[Alyssa Weber](https://github.com/Alyssa-Weber)
