---
output:
  pdf_document: default
  html_document: default
---
# Hockey EDA Project

This project is a part of the Portfolio for [Alyssa-Weber](https://github.com/Alyssa-Weber/Portfolio.git)

#### -- Project Status: [Completed]

## Project Intro/Objective

This project handled data from different sources including flat files, HTML, and APIS that described NHL records. Each source required five data cleaning steps and the results were merged together into a single data frame. 

### Methods Used

-   Data Collection
-   Source cleaning on flat files, HTML, and API
-   Jupyter Notebook / Python
-   Data Visualizations

## Project Description

-   This project is composed of three NHL record files that began in different formats including a flat file, HTML, and API
-   Each source required a minimum of five cleaning steps (EDA)
-   After cleaning took place, the large files were merged into a single data rame
-   Five unique visualizations were created from the results to showcase spread and trends within the data. 

## Needs of this project

-   data collection
-   EDA
-   write-up/reporting

## Featured Deliverables

-   [ipynb file](https://github.com/Alyssa-Weber/Portfolio/blob/main/%235%20-%20Hockey%20EDA%20Project/Hockey%20EDA%20Project.ipynb)
-   [pdf](https://github.com/Alyssa-Weber/Portfolio/blob/main/%235%20-%20Hockey%20EDA%20Project/Hockey%20EDA%20Project.pdf)

## Contributing Members

[Alyssa Weber](https://github.com/Alyssa-Weber)
