---
output:
  pdf_document: default
  html_document: default
---
# Gymnastics Scores Project

This project is a part of the Portfolio for [Alyssa-Weber](https://github.com/Alyssa-Weber/Portfolio.git)

#### -- Project Status: [Completed]

## Project Intro/Objective

This project aims to showcases the EDA process in the R environment by combining several spreadsheets into a single cohesive data frame.

### Methods Used

-   EDA in R Environment
-   R Markdown write-up 

## Project Description

-   This projects uses R Markdown to set up the process for a formal research based project
-   Uses personal data from competitive gymnastics to explore if there are any predictive characteristics in early gymnastics meets
- Showcases ReacXL, GGPlot 2, and dyplr. Multiple xlsx spreadsheets were read, combined, and modified to produce a single cohesive data frame that can later be used for modeling. 
- Uses box plots and and scatterplots to visualize the data. 
- A brief analysis using linear regression is also featured.


## Needs of this project

-   data collection/ research
-   write-up/reporting

## Featured Deliverables

-   [RMarkdown File](https://github.com/Alyssa-Weber/Portfolio/blob/main/%233%20-%20Gymnastics%20Scores%20Project/Predicting-Gymnastics-Scores.Rmd)
-   [PDF](https://github.com/Alyssa-Weber/Portfolio/blob/main/%233%20-%20Gymnastics%20Scores%20Project/Predicting-Gymnastics-Scores.pdf)

## Contributing Members

[Alyssa Weber](https://github.com/Alyssa-Weber)
