---
output:
  pdf_document: default
  html_document: default
---
# Social Emotional Learning Project

This project is a part of the Portfolio for [Alyssa-Weber](https://github.com/Alyssa-Weber/Portfolio.git)

#### -- Project Status: [Completed]

## Project Intro/Objective

This project aims to showcase social emotional self reported levels through the lens of statistical analysis. The objective was to test if relationship skill scores impact overall social emotional scores with statistical significance. 

### Methods Used

-   Data Collection
-   EDA
-   Jupyter Notebook/ Python
-   Informal statistical write up

## Project Description

-   Uses personal data collected from my 2022 class of students including strands of social emotional self-reported scores. 
-   Shows statistical images including PMF, CDF, and probability plots. 
-   Calculates different correlations including Pearson and Spearman
-   Conducts Hypothesis testing and Regression analysis

## Needs of this project

-   data collection/ research
-   write-up/reporting
-   statistical modeling

## Featured Deliverables

-   [ipynb file](https://github.com/Alyssa-Weber/Portfolio/blob/main/%234%20-%20Social%20Emotional%20Learning%20Project/SEL%20Project.ipynb)
-   [pdf](https://github.com/Alyssa-Weber/Portfolio/blob/main/%234%20-%20Social%20Emotional%20Learning%20Project/SEL%20Project.pdf)

## Contributing Members

[Alyssa Weber](https://github.com/Alyssa-Weber)
