---
output:
  pdf_document: default
  html_document: default
---
# Heart Disease Project

This project is a part of the Portfolio for [Alyssa-Weber](https://github.com/Alyssa-Weber/Portfolio.git)

#### -- Project Status: [Completed]

## Project Intro/Objective

This project contains a formal presentation regarding the ability to predict heart disease.

### Methods Used

-   Data Collection
-   White paper style write-up
-   Data Exploration
-   Modeling: Logistic Regression and Decision Tree

## Project Description

-   This project includes a formal APA style write-up, a formal presentation to the intended audience with recordings, and code. 
-   Data was found on Kaggle
-   The goal was to classify patients as either having or not having heart disease. 
-   The write up includes a business problem, background knowledge, data exploration, methods, analysis, conclusion, assumptions, and ethical considerations.
-   The presentation was geared towards medical professionals with the hopes that they could weigh the model proposal against traditional methods for predicting heart disease. 


## Featured Deliverables

-   [Paper](https://github.com/Alyssa-Weber/Portfolio/blob/main/%238%20-%20Heart%20Disease/Heart%20Disease%20White%20Paper.pdf)
-   [Presentation](https://github.com/Alyssa-Weber/Portfolio/blob/main/%238%20-%20Heart%20Disease/Heart%20Disease%20Presentation.pptx)
-   [Code - ipnyb](https://github.com/Alyssa-Weber/Portfolio/blob/main/%238%20-%20Heart%20Disease/Heart%20Disease%20Code.ipynb)

## Contributing Members

[Alyssa Weber](https://github.com/Alyssa-Weber)
